name: play_on
description: PlayOn

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  #Service Locator
  get_it: ^7.2.0

  #UI Layer
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1

  #Domain
  dartz: ^0.10.1
  equatable: ^2.0.3

  #Data
  connectivity_plus: ^2.3.2

  #Data - Remote
  url_launcher: ^6.1.2
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/