name: play_on
description: PlayOn

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  #Service Locator
  get_it: ^7.2.0

  #UI Layer
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.0
  cached_network_image: ^3.2.0
  google_fonts: ^2.2.0

  #Domain
  dartz: ^0.10.1
  equatable: ^2.0.3

  #Data
  connectivity_plus: ^2.2.0

  #Data - Remote
  url_launcher: ^6.0.17
  dio: ^4.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/